services:
  - type: web
    name: college-entry-app
    env: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: SECRET_KEY
      - key: SQLALCHEMY_DATABASE_URI
      - key: ACCOUNT_SID
      - key: AUTH_TOKEN
      - key: PH_NO
