services:
  - type: web
    name: college-entry-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: SQLALCHEMY_DATABASE_URI
        sync: false
      - key: ACCOUNT_SID
        sync: false
      - key: AUTH_TOKEN
        sync: false
      - key: PH_NO
        sync: false
